name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag noam070/webapp:${{ github.run_number }}-${GITHUB_SHA}
    - name: docker login
      run: docker login -u ${{ vers.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: docker push
      run: docker push noam070/webapp:${{ github.run_number }}-${GITHUB_SHA}
    
